name: Bootstrap renv cache

on:
  workflow_dispatch:    # run manually only

jobs:
  bootstrap_cache:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.4.1"

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-R-${{ hashFiles('**/renv.lock') }}
          restore-keys: ${{ runner.os }}-R-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev libssl-dev libxml2-dev libpng-dev libjpeg-dev libcairo2-dev \
            libgit2-dev libglpk-dev libtiff-dev libfftw3-dev libgdal-dev libgeos-dev libproj-dev \
            libv8-dev libudunits2-dev pkg-config

      - name: Restore renv packages
        run: |
          Rscript -e 'install.packages("renv", repos = "https://cran.rstudio.com")'
          Rscript -e 'renv::restore()'
